"""Add security fields: has_used_trial and transaction_id

Revision ID: 15700a9a0cb4
Revises: a6b88a4f6ca7
Create Date: 2026-03-09 19:52:34.944354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15700a9a0cb4'
down_revision: Union[str, Sequence[str], None] = 'a6b88a4f6ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postbacks', sa.Column('transaction_id', sa.String(), nullable=True))
    op.add_column('postbacks', sa.Column('status', sa.String(), nullable=False, server_default='processed'))
    op.create_index(op.f('ix_postbacks_transaction_id'), 'postbacks', ['transaction_id'], unique=True)
    
    # Исправлено: добавлен server_default='false' для старых записей
    op.add_column('users', sa.Column('has_used_trial', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_used_trial')
    op.drop_index(op.f('ix_postbacks_transaction_id'), table_name='postbacks')
    op.drop_column('postbacks', 'status')
    op.drop_column('postbacks', 'transaction_id')
    # ### end Alembic commands ###